---
title: "Interactive tool for prioritization and targeting workflow for the Excellence in Agronomy (EiA) platform"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
  orientation: row
  vertical_layout: scroll
---


```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(sf)
library(leaflet)
library(DT)


pdf(NULL)

# # http://benhay.es/posts/building-shiny-dashboards/
map <- readRDS("level1_KPI.rds")
df <- st_drop_geometry(map)
```


Sidebar {.sidebar data-width=400}
=====================================

#### **Individual Level Filters**

```{r level_inputs}

leveloptions <- sort(c("Level 1: Importance", "Level 2: Urgency", "Level 3: Enabler"))

checkboxGroupInput("level_checkbox",
                   "Level:",
                   choices = leveloptions,
                   selected = leveloptions[1]
                   )
```

<hr/>

#### **KPI selector: Level 1**

```{r level_1_KPI}

# rural population density
popmin <- floor(min(df$rural_pop_density_sq_km, na.rm = TRUE))
popmax <- ceiling(max(df$rural_pop_density_sq_km, na.rm = TRUE))

sliderInput("rural_pop_slider",
            "Rural population density/sq km:",
            min = popmin,
            max = popmax,
            value = c(popmin, popmax),
            step = 1,
            sep = NULL
          )

# agriculture land availability
aglandmin <- floor(min(df$cropland_ha_capita, na.rm = TRUE))
aglandmax <- ceiling(max(df$cropland_ha_capita, na.rm = TRUE))

sliderInput("ag_land_slider",
            "Agriculture land (ha) per capita:",
            min = aglandmin,
            max = aglandmax,
            value = c(aglandmin, aglandmax),
            step = 0.5,
            sep = NULL
          )
```

#### **KPI selector: Level 2**

#### **KPI selector: Level 3**

#### **KPI selector: Level 4**

Mapping priority areas
=====================================

```{r leaflet_map}

pal <- colorBin(
  palette = "viridis", domain = map$rural_pop_density_sq_km,
  bins = seq(popmin, popmax, by = 50)
)

map$labels <- paste0(
  "<strong> Country: </strong> ",
  map$NAME_0, "<br/> ",
  "<strong> Farming system: </strong> ",
  map$frm_sys, "<br/> ",
  "<strong> Rural Population Density: </strong> ",
  map$rural_pop_density_sq_km, "<br/> ",
  "<strong> Cropland (ha)/capita: </strong> ",
  map$cropland_ha_capita, "<br/> "
) %>%
  lapply(htmltools::HTML)

mapFiltered <- reactive({
  k1 <- which(map$rural_pop_density_sq_km >= input$rural_pop_slider[1] &
                           map$rural_pop_density_sq_km <= input$rural_pop_slider[2])
  k2 <- which(map$cropland_ha_capita >= input$ag_land_slider[1] &
                           map$cropland_ha_capita <= input$ag_land_slider[2])
  map[sort(unique(c(k1, k2))), ]
})


renderLeaflet({
  if(nrow(mapFiltered()) == 0){
  return(NULL)
  }
  
  leaflet(data=mapFiltered()) %>%
  addTiles() %>%
  setView(lng = 0, lat = 30, zoom = 3) %>%
  addPolygons(
    fillColor = ~ pal(cropland_ha_capita),
    color = "#444444", weight = 1, smoothFactor = 0.5,
    fillOpacity = 0.5,
    label = ~labels,
    highlight = highlightOptions(
      color = "white", weight = 2,
      bringToFront = TRUE
    )
  ) %>%
  leaflet::addLegend(
    pal = pal, values = ~rural_pop_density_sq_km,
    opacity = 0.7, title = "rural_pop_density_sq_km"
  )

})

# renderLeaflet({
#   leaflet() %>%
#     addTiles() %>%
#     setView(lat = 0, lng = 30, zoom = 4) %>%
#     # Add two tiles
#     addProviderTiles("Esri.WorldImagery", group="ESRI WorldImagery") %>%
#     # Add the control widget
#     addLayersControl(overlayGroups = c("L1 Map of important areas","L2 Map of urgent areas",
#                                        "L3 Map of enable areas", "Composite score maps") , 
#                      baseGroups = c("ESRI WorldImagery"),
#                      options = layersControlOptions(collapsed = FALSE))  
# })
```


Explore/download data
=====================================

```{r render_datatable}
DT::renderDataTable({
  df <- st_drop_geometry(mapFiltered())
  dat <- df %>%
    select(NAME_0, frm_sys, area_sq_km, rural_pop, cropland_area_ha, rural_pop_density_sq_km, cropland_ha_capita)
  colnames(dat) <- c("Country", "Farming System", "Area of farming system/country",
           "Total rural population", "Cropland area (in ha)",
           "Rural population density/sqkm",
           "Cropland availability (ha)/per capita")
  
DT::datatable(dat,
                rownames = FALSE,
                extensions = 'Buttons',
                options = list(pageLength = 10, 
                               scrollX = T,
                               filter = "top",
                               dom = 'Bfrtip',
                               buttons = c('csv', 'copy', 'print')

                )) %>%
    formatStyle(columns = seq(1, 21, 1), fontSize = "9pt")
})
```


###

Background
=====================================



###

